---
#
# Demonstrate a workflow execution
#
name: Test Conda Image
on:
  workflow_dispatch:
    # Workflow Dispatch inputs.  Provide them in CLI or in Web UI workflow dispatch trigger
    # SEE: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
    inputs:

      action_version:
        description: The git ref to an action to run
        required: false
        default: demo

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build a conda image
        uses: markllama/action-conda-image@demo
        with:
          registry-username: markllama
          registry-password: foo
          image-name: bar
          image-tag: gronk

# restrict this script to do nothing, Relax this for your tests
# SEE: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
#permissions: { }
