---
#
# Demonstrate a workflow execution
#
name: Test Conda Image
on:
  workflow_dispatch:
    # Workflow Dispatch inputs.  Provide them in CLI or in Web UI workflow dispatch trigger
    # SEE: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
    inputs:
      greeting:
        description: How to greet the world
        required: true
        default: 'Hello World'

      action_version:
        description: The git ref to an action to run
        required: true

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Conda
        run: |
          echo ${{ inputs.greeting }}

      - name: Build a conda image
        uses: markllama/action-conda-image@demo
          
      

# restrict this script to do nothing, Relax this for your tests
# SEE: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
#permissions: { }
