---
#
# Demonstrate a workflow execution
#
name: Test Conda Image
on:
  workflow_dispatch:
    # Workflow Dispatch inputs.  Provide them in CLI or in Web UI workflow dispatch trigger
    # SEE: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
    inputs:

      action_version:
        description: The git ref to an action to run
        default: demo

      conda_python:
        description: Which version of python to use
        default: "3.10"

      conda_env:
        description: Select an env file to test
        type: choice
        options:
          - "conda-env.yaml"
          - "conda-env-floating-python.yaml"
          - "conda-env-no-python.yaml"
        default: "conda-env.yaml"
          
      force_build:
        description: Force a build even if it exists
        default: false


jobs:
  build_conda_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build a conda image
        uses: markllama/action-conda-image@demo
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GHCR_TOKEN }}
          
          #image-name: test-conda-build
          image-tag: "py${{ inputs.conda_python }}"
          force-build: "${{ inputs.force_build }}"

          conda-python: "${{ inputs.conda_python }}"

          conda_env: "${{ inputs.conda_env }}"

# restrict this script to do nothing, Relax this for your tests
# SEE: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
#permissions: { }
